services:
  app:
    build: .
    container_name: app_bank
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

  db:
    image: postgres:17-alpine
    container_name: pg_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bank_rest
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./base_data:/var/lib/postgresql/data

